# Generated by Django 3.0.4 on 2020-03-23 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Campus')),
            ],
        ),
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_id', models.TextField()),
                ('name', models.TextField(max_length=100)),
                ('time_clicked', models.DateTimeField(auto_now=True)),
                ('click_type', models.PositiveSmallIntegerField(choices=[(0, 'Single'), (1, 'Double'), (2, 'Long')])),
                ('battery', models.PositiveSmallIntegerField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Location')),
            ],
        ),
    ]
